env:
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_WORKING_DIR: "/tmp/ci"
    rclone_config: "ENCRYPTED[300de49bcaaa984d4399aef410d6ae5d19ca77b42af11431238f5d13dc953e89717e1dd90780890bb274aa505be9f8d6]"

task:
    name: new88
    timeout_in: 120m
    container:
      image: ubuntu:latest
      cpu: 16
      memory: 24G
    system_update_script:
      - ./system_update
    neofetch_script:
      - ./neofetch
    specification_script:
      - ./specification
#    download_ccache_script:
#      - ./download_ccache
    sync_script:
      - ./sync
    build_script:
      - ./build
#    upload_ccache_script:
#      - ./upload_ccache
      
