#!/bin/bash

echo "Downloading previous ccache . . . . . ."
curl https://transfer.sh/s7Uow/ccache-lineagex.tar.gz -o ccache-lineagex.tar.gz

cd /tmp # Where to download cccahe
#time aria2c $url -x16 -s50
time tar xf ccache-lineagex.tar.gz
rm -rf ccache-lineagex.tar.gz
