#!/bin/bash

echo "Downloading previous ccache . . . . . ."

cd /tmp
curl https://transfer.sh/s7Uow/ccache-fluid-11.tar.gz -o ccache-fluid-11.tar.gz
time tar xf ccache-fluid-11.tar.gz
rm -rf ccache-fluid-11.tar.gz
