#!/bin/bash

MANIFEST=https://github.com/PixysOS/manifest
BRANCH=eleven

mkdir -p /tmp/rom
cd /tmp/rom

# Repo init command
repo init --no-repo-verify --depth=1 -u "$MANIFEST" -b "$BRANCH" -g default,-device,-mips,-darwin,-notdefault
git config --global user.name unnamed877
git config --global user.email unnamed877@protonmail.com

# Sync source with -q
repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j$(nproc --all) || repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j16

# Device Tree
git clone https://github.com/unnamed877/android_device_xiaomi_certus -b pixys/11 device/xiaomi/certus
git clone https://github.com/wulan17/proprietary_vendor_xiaomi -b 11 vendor/xiaomi
git clone https://gitlab.com/wulan17/prebuilts_gcc_linux-x86_arm_arm-none-linux-gnueabihf -b 9.2 prebuilts/gcc/linux-x86/arm/arm-none-linux-gnueabihf-9.2
git clone https://github.com/wulan17/android_kernel_xiaomi_mt6765 -b 11-nad kernel/xiaomi/mt6765

# For fix RIL problem in LOS Android Q based ROM
#rm -rf packages/services/Telephony
#git clone https://github.com/LineageOS/android_packages_services_Telephony -b lineage-17.1 packages/services/Telephony

# Codec Patch maybe :p
cd frameworks/av
wget https://github.com/SamarV-121/android_vendor_extra/raw/lineage-18.1/patches/frameworks/av/0005-Don-t-fail-AAC-decoding-if-DRC-parameter-isn-t-avail.patch
git am 0005-Don-t-fail-AAC-decoding-if-DRC-parameter-isn-t-avail.patch
cd /tmp/rom

# Fix Install folder gone issue
cd build/patch
wget https://github.com/Komodo-OS-Rom/build/commit/298ea6830037c69b5299f57b6cc3aefe04ad9ae5.patch
git am 298ea6830037c69b5299f57b6cc3aefe04ad9ae5.patch
cd /tmp/rom
