#!/bin/bash

echo "Updating System . . ."
apt-get update && apt-get --yes --force-yes upgrade
apt-get --yes --force-yes install wget
apt-get --yes --force-yes install wget curl git aria aria2 aria2c

# set noninteractive installation
export DEBIAN_FRONTEND=noninteractive
#install tzdata package
apt-get install -y tzdata
# set your timezone
ln -fs /usr/share/zoneinfo/Asia/Makassar /etc/localtime
dpkg-reconfigure --frontend noninteractive tzdata

#installing repo
mkdir ~/.bin
curl https://storage.googleapis.com/git-repo-downloads/repo > ~/.bin/repo
chmod a+x ~/.bin/repo
echo "export PATH=~/bin:$PATH" >> ~/.bashrc

wget 'https://storage.googleapis.com/git-repo-downloads/repo' -P /usr/local/sbin/
chmod +x /usr/local/sbin/repo

repo

echo "Installing some dependencies . . . . . ."
apt-get --yes --force-yes install ccache git-core gnupg wget curl flex bison build-essential zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z1-dev libgl1-mesa-dev libxml2-utils xsltproc unzip fontconfig bc kmod neofetch htop
apt-get --yes --force-yes install openssh-server screen python git openjdk-8-jdk android-tools-adb bc bison
apt-get --yes --force-yes install bison build-essential curl flex g++-multilib gcc-multilib gnupg gperf imagemagick
apt-get --yes --force-yes install lib32ncurses-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev
apt-get --yes --force-yes install libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc
apt-get --yes --force-yes install yasm zip zlib1g-dev libtinfo5 libncurses5
